version: '3'

services: 
  tensorflow-serving:
    build: 
      context: ./services/tensorflow-serving
      dockerfile: Dockerfile.tf   
    environment:  
      MODEL_NAME: my_model
    expose: 
      - "8501"
    depends_on: 
      - web
  web:
    build:
      context: ./services/web/flask
      dockerfile: Dockerfile.flask
    volumes: 
      - sql_data:/app/database
    command: gunicorn --bind 0.0.0.0:5000 manage:flask_app
    expose:
      - 5000
  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 1337:443

volumes:
  sql_data:
